
USER_LIB_PATH := $(shell git rev-parse --show-toplevel)/lib
ARDUINO_LIBS = FastLED
BOARD_TAG    = nano
BOARD_SUB    = atmega328
ARDUINO_PORT = /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

include /usr/share/arduino/Arduino.mk
